export interface ToolBinding {
  toolCode: string;
  capabilityCode: string;
  domain: string;
  binding: string | null;
  available: boolean;
  reason?: 'SOURCE_REQUIRED' | 'FUTURE_TOOL' | 'AVAILABLE';
}

export const TOOL_BINDING_REGISTRY: Record<string, ToolBinding> = {
  // 1. Account & Company -> market-intelligence / crm
  'account.read': {
    toolCode: 'market-intelligence',
    capabilityCode: 'account.read',
    domain: 'account',
    binding: 'AccountIntelligenceService.getIntelligence',
    available: true,
    reason: 'AVAILABLE',
  },
  'account.search': {
    toolCode: 'market-intelligence',
    capabilityCode: 'account.search',
    domain: 'account',
    binding: 'AccountIntelligenceService.searchAccounts',
    available: true,
    reason: 'AVAILABLE',
  },
  'account.research': {
    toolCode: 'market-intelligence',
    capabilityCode: 'account.research',
    domain: 'account',
    binding: 'AccountIntelligenceService.getIntelligence',
    available: true,
    reason: 'AVAILABLE',
  },
  'account.score': {
    toolCode: 'market-intelligence',
    capabilityCode: 'account.score',
    domain: 'account',
    binding: 'AccountIntelligenceService.calculateScore',
    available: true,
    reason: 'AVAILABLE',
  },
  'company.read': {
    toolCode: 'crm',
    capabilityCode: 'company.read',
    domain: 'company',
    binding: 'PrismaCompanyRepository.findById',
    available: true,
    reason: 'AVAILABLE',
  },
  'company.search': {
    toolCode: 'crm',
    capabilityCode: 'company.search',
    domain: 'company',
    binding: 'PrismaCompanyRepository.search',
    available: true,
    reason: 'AVAILABLE',
  },
  'company.enrich': {
    toolCode: 'prospecting',
    capabilityCode: 'company.enrich',
    domain: 'company',
    binding: 'ProspectingEnrichmentService.enrichCompany',
    available: true,
    reason: 'AVAILABLE',
  },

  // 2. Lead & ICP -> crm / market-intelligence
  'lead.read': {
    toolCode: 'crm',
    capabilityCode: 'lead.read',
    domain: 'lead',
    binding: 'PrismaLeadRepository.findById',
    available: true,
    reason: 'AVAILABLE',
  },
  'lead.search': {
    toolCode: 'crm',
    capabilityCode: 'lead.search',
    domain: 'lead',
    binding: 'PrismaLeadRepository.findMany',
    available: true,
    reason: 'AVAILABLE',
  },
  'lead.enrich': {
    toolCode: 'prospecting',
    capabilityCode: 'lead.enrich',
    domain: 'lead',
    binding: 'ProspectingEnrichmentService.enrichLead',
    available: true,
    reason: 'AVAILABLE',
  },
  'lead.score': {
    toolCode: 'market-intelligence',
    capabilityCode: 'lead.score',
    domain: 'lead',
    binding: 'AccountIntelligenceService.scoreLead',
    available: true,
    reason: 'AVAILABLE',
  },
  'lead.qualify': {
    toolCode: 'crm',
    capabilityCode: 'lead.qualify',
    domain: 'lead',
    binding: 'QualificationMatrixService.evaluate',
    available: true,
    reason: 'AVAILABLE',
  },
  'lead.update': {
    toolCode: 'crm',
    capabilityCode: 'lead.update',
    domain: 'lead',
    binding: 'PrismaLeadRepository.update',
    available: true,
    reason: 'AVAILABLE',
  },
  'icp.read': {
    toolCode: 'market-intelligence',
    capabilityCode: 'icp.read',
    domain: 'market',
    binding: 'MarketIntelligenceTaxonomy.getIcp',
    available: true,
    reason: 'AVAILABLE',
  },
  'icp.analyze': {
    toolCode: 'market-intelligence',
    capabilityCode: 'icp.analyze',
    domain: 'market',
    binding: 'AccountIntelligenceService.analyzeIcpFit',
    available: true,
    reason: 'AVAILABLE',
  },

  // 3. Market & Intelligence
  'market.read': {
    toolCode: 'market-intelligence',
    capabilityCode: 'market.read',
    domain: 'market',
    binding: 'MarketIntelligenceRepository.getOverview',
    available: true,
    reason: 'AVAILABLE',
  },
  'market.research': {
    toolCode: 'market-intelligence',
    capabilityCode: 'market.research',
    domain: 'market',
    binding: 'MarketIntelligenceRepository.researchSector',
    available: true,
    reason: 'AVAILABLE',
  },
  'decision_maker.search': {
    toolCode: 'prospecting',
    capabilityCode: 'decision_maker.search',
    domain: 'market',
    binding: 'ProspectingToolsService.searchDecisionMakers',
    available: true,
    reason: 'AVAILABLE',
  },
  'trigger_event.read': {
    toolCode: 'market-intelligence',
    capabilityCode: 'trigger_event.read',
    domain: 'market',
    binding: 'AccountIntelligenceService.getAccountSignals',
    available: true,
    reason: 'AVAILABLE',
  },
  'news.read': {
    toolCode: 'market-intelligence',
    capabilityCode: 'news.read',
    domain: 'market',
    binding: 'AccountIntelligenceService.getNewsMentions',
    available: true,
    reason: 'AVAILABLE',
  },
  'territory.read': {
    toolCode: 'market-intelligence',
    capabilityCode: 'territory.read',
    domain: 'market',
    binding: 'MarketIntelligenceRepository.getTerritories',
    available: true,
    reason: 'AVAILABLE',
  },

  // 4. Outbound & Cadence
  'outbound.plan': {
    toolCode: 'cadence',
    capabilityCode: 'outbound.plan',
    domain: 'outbound',
    binding: 'CadenceService.getOutboundStrategy',
    available: true,
    reason: 'AVAILABLE',
  },
  'outbound.personalize': {
    toolCode: 'cadence',
    capabilityCode: 'outbound.personalize',
    domain: 'outbound',
    binding: 'BDRAgent.personalizeApproach',
    available: true,
    reason: 'AVAILABLE',
  },
  'outbound.generate_message': {
    toolCode: 'cadence',
    capabilityCode: 'outbound.generate_message',
    domain: 'outbound',
    binding: 'BDRAgent.generateOutboundMessage',
    available: true,
    reason: 'AVAILABLE',
  },
  'outbound.generate_script': {
    toolCode: 'cadence',
    capabilityCode: 'outbound.generate_script',
    domain: 'outbound',
    binding: 'BDRAgent.generateColdCallScript',
    available: true,
    reason: 'AVAILABLE',
  },
  'cadence.read': {
    toolCode: 'cadence',
    capabilityCode: 'cadence.read',
    domain: 'cadence',
    binding: 'CadenceService.getCadence',
    available: true,
    reason: 'AVAILABLE',
  },
  'cadence.suggest': {
    toolCode: 'cadence',
    capabilityCode: 'cadence.suggest',
    domain: 'cadence',
    binding: 'CadenceService.suggestNextStep',
    available: true,
    reason: 'AVAILABLE',
  },
  'cadence.execute': {
    toolCode: 'cadence',
    capabilityCode: 'cadence.execute',
    domain: 'cadence',
    binding: 'CadenceService.executeStep',
    available: true,
    reason: 'AVAILABLE',
  },

  // 5. Meetings & Calendar
  'meeting.read': {
    toolCode: 'calendar',
    capabilityCode: 'meeting.read',
    domain: 'meeting',
    binding: 'PrismaCalendarSchedulerPort.listMeetings',
    available: true,
    reason: 'AVAILABLE',
  },
  'meeting.prepare': {
    toolCode: 'meetings',
    capabilityCode: 'meeting.prepare',
    domain: 'meeting',
    binding: 'MeetingPreparationService.buildDossier',
    available: true,
    reason: 'AVAILABLE',
  },
  'meeting.analyze': {
    toolCode: 'meetings',
    capabilityCode: 'meeting.analyze',
    domain: 'meeting',
    binding: 'CopilotoIaService.analyzeMeeting',
    available: true,
    reason: 'AVAILABLE',
  },
  'meeting.request': {
    toolCode: 'calendar',
    capabilityCode: 'meeting.request',
    domain: 'meeting',
    binding: 'BookingRoutes.getPublicBookingLink',
    available: true,
    reason: 'AVAILABLE',
  },
  'meeting.schedule': {
    toolCode: 'calendar',
    capabilityCode: 'meeting.schedule',
    domain: 'meeting',
    binding: 'PrismaCalendarSchedulerPort.scheduleMeeting',
    available: true,
    reason: 'AVAILABLE',
  },

  // 6. Activities & Qualification
  'activity.read': {
    toolCode: 'activities',
    capabilityCode: 'activity.read',
    domain: 'activity',
    binding: 'PrismaActivityRepository.findMany',
    available: true,
    reason: 'AVAILABLE',
  },
  'activity.create': {
    toolCode: 'activities',
    capabilityCode: 'activity.create',
    domain: 'activity',
    binding: 'PrismaActivityRepository.create',
    available: true,
    reason: 'AVAILABLE',
  },
  'activity.update': {
    toolCode: 'activities',
    capabilityCode: 'activity.update',
    domain: 'activity',
    binding: 'PrismaActivityRepository.update',
    available: true,
    reason: 'AVAILABLE',
  },
  'activity.analyze': {
    toolCode: 'activities',
    capabilityCode: 'activity.analyze',
    domain: 'activity',
    binding: 'CommercialIntelligenceUseCases.getActivityMetrics',
    available: true,
    reason: 'AVAILABLE',
  },
  'qualification.read': {
    toolCode: 'crm',
    capabilityCode: 'qualification.read',
    domain: 'qualification',
    binding: 'QualificationMatrixService.getMatrix',
    available: true,
    reason: 'AVAILABLE',
  },
  'qualification.evaluate': {
    toolCode: 'crm',
    capabilityCode: 'qualification.evaluate',
    domain: 'qualification',
    binding: 'SDRQualificationAgent.evaluateLead',
    available: true,
    reason: 'AVAILABLE',
  },

  // 7. Deals & Pipeline
  'deal.read': {
    toolCode: 'crm',
    capabilityCode: 'deal.read',
    domain: 'deal',
    binding: 'PrismaDealRepository.findById',
    available: true,
    reason: 'AVAILABLE',
  },
  'deal.analyze': {
    toolCode: 'crm',
    capabilityCode: 'deal.analyze',
    domain: 'deal',
    binding: 'CloserAgent.analyzeDeal',
    available: true,
    reason: 'AVAILABLE',
  },
  'deal.update': {
    toolCode: 'crm',
    capabilityCode: 'deal.update',
    domain: 'deal',
    binding: 'PrismaDealRepository.update',
    available: true,
    reason: 'AVAILABLE',
  },
  'deal.move_stage': {
    toolCode: 'crm',
    capabilityCode: 'deal.move_stage',
    domain: 'deal',
    binding: 'PrismaDealRepository.moveStage',
    available: true,
    reason: 'AVAILABLE',
  },
  'pipeline.read': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'pipeline.read',
    domain: 'pipeline',
    binding: 'CommercialIntelligenceUseCases.getPipelineSummary',
    available: true,
    reason: 'AVAILABLE',
  },
  'pipeline.analyze': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'pipeline.analyze',
    domain: 'pipeline',
    binding: 'CommercialIntelligenceAiService.analyzePipeline',
    available: true,
    reason: 'AVAILABLE',
  },

  // 8. Forecast & Revenue Intelligence
  'forecast.read': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'forecast.read',
    domain: 'revenue',
    binding: 'CommercialIntelligenceUseCases.getForecastRollup',
    available: true,
    reason: 'AVAILABLE',
  },
  'forecast.explain': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'forecast.explain',
    domain: 'revenue',
    binding: 'CommercialIntelligenceAiService.explainForecast',
    available: true,
    reason: 'AVAILABLE',
  },
  'revenue.read': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'revenue.read',
    domain: 'revenue',
    binding: 'CommercialIntelligenceUseCases.getRevenuePerformance',
    available: true,
    reason: 'AVAILABLE',
  },
  'revenue.analyze': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'revenue.analyze',
    domain: 'revenue',
    binding: 'CommercialIntelligenceAiService.generateExecutiveBrief',
    available: true,
    reason: 'AVAILABLE',
  },
  'revenue.reconcile': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'revenue.reconcile',
    domain: 'revenue',
    binding: null,
    available: false,
    reason: 'SOURCE_REQUIRED',
  },
  'coverage.read': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'coverage.read',
    domain: 'revenue',
    binding: 'CommercialIntelligenceUseCases.getPipelineCoverage',
    available: true,
    reason: 'AVAILABLE',
  },
  'conversion.read': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'conversion.read',
    domain: 'revenue',
    binding: 'CommercialIntelligenceUseCases.getConversionRates',
    available: true,
    reason: 'AVAILABLE',
  },
  'sales_cycle.read': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'sales_cycle.read',
    domain: 'revenue',
    binding: 'CommercialIntelligenceUseCases.getSalesCycleDuration',
    available: true,
    reason: 'AVAILABLE',
  },
  'aging.read': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'aging.read',
    domain: 'revenue',
    binding: 'CommercialIntelligenceUseCases.getAgingDeals',
    available: true,
    reason: 'AVAILABLE',
  },
  'loss.read': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'loss.read',
    domain: 'revenue',
    binding: 'CommercialIntelligenceUseCases.getLossAnalysis',
    available: true,
    reason: 'AVAILABLE',
  },
  'health_score.read': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'health_score.read',
    domain: 'revenue',
    binding: 'CommercialIntelligenceUseCases.getAccountHealthScore',
    available: true,
    reason: 'AVAILABLE',
  },
  'scenario.analyze': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'scenario.analyze',
    domain: 'revenue',
    binding: 'CommercialIntelligenceAiService.modelScenarios',
    available: true,
    reason: 'AVAILABLE',
  },
  'executive.read': {
    toolCode: 'commercial-intelligence',
    capabilityCode: 'executive.read',
    domain: 'revenue',
    binding: 'CommercialIntelligenceUseCases.getExecutiveCockpit',
    available: true,
    reason: 'AVAILABLE',
  },

  // 9. Proposal, Pricing & ROI
  'proposal.read': {
    toolCode: 'crm',
    capabilityCode: 'proposal.read',
    domain: 'proposal',
    binding: 'PrismaCrmDocumentRepository.findProposals',
    available: true,
    reason: 'AVAILABLE',
  },
  'proposal.generate': {
    toolCode: 'crm',
    capabilityCode: 'proposal.generate',
    domain: 'proposal',
    binding: 'CloserAgent.generateProposal',
    available: true,
    reason: 'AVAILABLE',
  },
  'pricing.read': {
    toolCode: 'pricing',
    capabilityCode: 'pricing.read',
    domain: 'pricing',
    binding: 'PricingCatalogService.getTiers',
    available: true,
    reason: 'AVAILABLE',
  },
  'pricing.suggest': {
    toolCode: 'pricing',
    capabilityCode: 'pricing.suggest',
    domain: 'pricing',
    binding: 'CloserAgent.suggestPricing',
    available: true,
    reason: 'AVAILABLE',
  },
  'pricing.approve': {
    toolCode: 'pricing',
    capabilityCode: 'pricing.approve',
    domain: 'pricing',
    binding: 'CommercialManagementService.approvePricing',
    available: true,
    reason: 'AVAILABLE',
  },
  'discount.suggest': {
    toolCode: 'pricing',
    capabilityCode: 'discount.suggest',
    domain: 'pricing',
    binding: 'CloserAgent.calculateDiscountImpact',
    available: true,
    reason: 'AVAILABLE',
  },
  'discount.approve': {
    toolCode: 'pricing',
    capabilityCode: 'discount.approve',
    domain: 'pricing',
    binding: 'CommercialManagementService.approveDiscount',
    available: true,
    reason: 'AVAILABLE',
  },
  'roi.calculate': {
    toolCode: 'proposal',
    capabilityCode: 'roi.calculate',
    domain: 'proposal',
    binding: 'CloserAgent.calculateRoi',
    available: true,
    reason: 'AVAILABLE',
  },

  // 10. Contracts & Signatures
  'contract.read': {
    toolCode: 'contracts',
    capabilityCode: 'contract.read',
    domain: 'contract',
    binding: 'PrismaSignatureRequestRepository.listContracts',
    available: true,
    reason: 'AVAILABLE',
  },
  'contract.analyze': {
    toolCode: 'contracts',
    capabilityCode: 'contract.analyze',
    domain: 'contract',
    binding: 'ContractSignatureAgent.analyzeContract',
    available: true,
    reason: 'AVAILABLE',
  },
  'contract.generate': {
    toolCode: 'contracts',
    capabilityCode: 'contract.generate',
    domain: 'contract',
    binding: 'DocumentSignatureApplication.createDraft',
    available: true,
    reason: 'AVAILABLE',
  },
  'contract.validate': {
    toolCode: 'contracts',
    capabilityCode: 'contract.validate',
    domain: 'contract',
    binding: 'ContractSignatureAgent.validateData',
    available: true,
    reason: 'AVAILABLE',
  },
  'contract.request': {
    toolCode: 'contracts',
    capabilityCode: 'contract.request',
    domain: 'contract',
    binding: 'ContractSignatureAgent.requestIssuance',
    available: true,
    reason: 'AVAILABLE',
  },
  'contract.request_signature': {
    toolCode: 'cadence/signature',
    capabilityCode: 'contract.request_signature',
    domain: 'contract',
    binding: 'GovBrSignatureProviderPort.requestSignature',
    available: true,
    reason: 'AVAILABLE',
  },
  'signature.read': {
    toolCode: 'cadence/signature',
    capabilityCode: 'signature.read',
    domain: 'contract',
    binding: 'PrismaSignatureRequestRepository.findById',
    available: true,
    reason: 'AVAILABLE',
  },
  'signature.request': {
    toolCode: 'cadence/signature',
    capabilityCode: 'signature.request',
    domain: 'contract',
    binding: 'GovBrSignatureProviderPort.requestSignature',
    available: true,
    reason: 'AVAILABLE',
  },
  'signature.cancel': {
    toolCode: 'cadence/signature',
    capabilityCode: 'signature.cancel',
    domain: 'contract',
    binding: 'GovBrSignatureProviderPort.cancelSignature',
    available: true,
    reason: 'AVAILABLE',
  },

  // 11. Customer Success & Churn
  'customer.read': {
    toolCode: 'crm',
    capabilityCode: 'customer.read',
    domain: 'customer',
    binding: 'PrismaCompanyRepository.findActiveCustomers',
    available: true,
    reason: 'AVAILABLE',
  },
  'customer.health': {
    toolCode: 'analytics/churn',
    capabilityCode: 'customer.health',
    domain: 'customer',
    binding: 'ChurnPredictionService.getHealthIndex',
    available: true,
    reason: 'AVAILABLE',
  },
  'customer.lifecycle': {
    toolCode: 'analytics/churn',
    capabilityCode: 'customer.lifecycle',
    domain: 'customer',
    binding: 'ChurnRetentionAgent.getLifecycleStage',
    available: true,
    reason: 'AVAILABLE',
  },
  'churn.read': {
    toolCode: 'analytics/churn',
    capabilityCode: 'churn.read',
    domain: 'customer',
    binding: 'ChurnPredictionService.getRiskList',
    available: true,
    reason: 'AVAILABLE',
  },
  'churn.analyze': {
    toolCode: 'analytics/churn',
    capabilityCode: 'churn.analyze',
    domain: 'customer',
    binding: 'ChurnPredictionService.analyzeChurnRisk',
    available: true,
    reason: 'AVAILABLE',
  },
  'retention.plan': {
    toolCode: 'analytics/churn',
    capabilityCode: 'retention.plan',
    domain: 'customer',
    binding: 'ChurnRetentionAgent.proposeRetentionPlan',
    available: true,
    reason: 'AVAILABLE',
  },
  'renewal.read': {
    toolCode: 'crm',
    capabilityCode: 'renewal.read',
    domain: 'customer',
    binding: 'PrismaDealRepository.findRenewals',
    available: true,
    reason: 'AVAILABLE',
  },
  'revenue_at_risk.read': {
    toolCode: 'analytics/churn',
    capabilityCode: 'revenue_at_risk.read',
    domain: 'customer',
    binding: 'ChurnPredictionService.getRevenueAtRisk',
    available: true,
    reason: 'AVAILABLE',
  },

  // 12. CRM & Bitrix Integration
  'crm.read': {
    toolCode: 'crm',
    capabilityCode: 'crm.read',
    domain: 'crm',
    binding: 'PrismaLeadRepository.findMany',
    available: true,
    reason: 'AVAILABLE',
  },
  'crm.audit': {
    toolCode: 'bitrix',
    capabilityCode: 'crm.audit',
    domain: 'crm',
    binding: 'BitrixGuardianAgent.auditHygiene',
    available: true,
    reason: 'AVAILABLE',
  },
  'crm.suggest_update': {
    toolCode: 'crm',
    capabilityCode: 'crm.suggest_update',
    domain: 'crm',
    binding: 'CopilotoIaService.suggestFieldUpdates',
    available: true,
    reason: 'AVAILABLE',
  },
  'crm.duplicate_detect': {
    toolCode: 'crm',
    capabilityCode: 'crm.duplicate_detect',
    domain: 'crm',
    binding: 'BitrixGuardianAgent.detectDuplicates',
    available: true,
    reason: 'AVAILABLE',
  },
  'crm.stage_validate': {
    toolCode: 'crm',
    capabilityCode: 'crm.stage_validate',
    domain: 'crm',
    binding: 'BitrixGuardianAgent.validateStageRequirements',
    available: true,
    reason: 'AVAILABLE',
  },
  'crm.field_validate': {
    toolCode: 'crm',
    capabilityCode: 'crm.field_validate',
    domain: 'crm',
    binding: 'BitrixGuardianAgent.validateFields',
    available: true,
    reason: 'AVAILABLE',
  },
  'bitrix.read': {
    toolCode: 'bitrix',
    capabilityCode: 'bitrix.read',
    domain: 'integrations',
    binding: 'BitrixIntegrationService.getStatus',
    available: true,
    reason: 'AVAILABLE',
  },
  'bitrix.sync_status': {
    toolCode: 'bitrix',
    capabilityCode: 'bitrix.sync_status',
    domain: 'integrations',
    binding: 'BitrixSyncWorker.getQueueStatus',
    available: true,
    reason: 'AVAILABLE',
  },
  'bitrix.write': {
    toolCode: 'bitrix',
    capabilityCode: 'bitrix.write',
    domain: 'integrations',
    binding: 'BitrixWritebackService.enqueue',
    available: true,
    reason: 'AVAILABLE',
  },
  'bitrix.configure': {
    toolCode: 'bitrix',
    capabilityCode: 'bitrix.configure',
    domain: 'integrations',
    binding: 'BitrixConfigurationService.updateConfig',
    available: true,
    reason: 'AVAILABLE',
  },

  // 13. Finance, Billing & Invoicing (SOURCE_REQUIRED)
  'billing.read': {
    toolCode: 'billing',
    capabilityCode: 'billing.read',
    domain: 'billing',
    binding: null,
    available: false,
    reason: 'SOURCE_REQUIRED',
  },
  'billing.reconcile': {
    toolCode: 'billing',
    capabilityCode: 'billing.reconcile',
    domain: 'billing',
    binding: null,
    available: false,
    reason: 'SOURCE_REQUIRED',
  },
  'billing.analyze': {
    toolCode: 'billing',
    capabilityCode: 'billing.analyze',
    domain: 'billing',
    binding: null,
    available: false,
    reason: 'SOURCE_REQUIRED',
  },
  'invoice.read': {
    toolCode: 'billing',
    capabilityCode: 'invoice.read',
    domain: 'billing',
    binding: null,
    available: false,
    reason: 'SOURCE_REQUIRED',
  },
  'invoice.generate': {
    toolCode: 'billing',
    capabilityCode: 'invoice.generate',
    domain: 'billing',
    binding: null,
    available: false,
    reason: 'SOURCE_REQUIRED',
  },
  'payment.read': {
    toolCode: 'billing',
    capabilityCode: 'payment.read',
    domain: 'billing',
    binding: null,
    available: false,
    reason: 'SOURCE_REQUIRED',
  },

  // 14. Team & Management
  'team.read': {
    toolCode: 'team',
    capabilityCode: 'team.read',
    domain: 'team',
    binding: 'TeamService.listMembers',
    available: true,
    reason: 'AVAILABLE',
  },
  'team.manage': {
    toolCode: 'team',
    capabilityCode: 'team.manage',
    domain: 'team',
    binding: 'TeamService.updateMember',
    available: true,
    reason: 'AVAILABLE',
  },
  'team.performance': {
    toolCode: 'team',
    capabilityCode: 'team.performance',
    domain: 'team',
    binding: 'CommercialIntelligenceUseCases.getTeamPerformanceReport',
    available: true,
    reason: 'AVAILABLE',
  },
  'sla.read': {
    toolCode: 'team',
    capabilityCode: 'sla.read',
    domain: 'team',
    binding: 'CommercialIntelligenceUseCases.getFirstContactSla',
    available: true,
    reason: 'AVAILABLE',
  },
  'sla.analyze': {
    toolCode: 'team',
    capabilityCode: 'sla.analyze',
    domain: 'team',
    binding: 'CoordinatorCommercialAgent.analyzeSla',
    available: true,
    reason: 'AVAILABLE',
  },
  'alert.read': {
    toolCode: 'team',
    capabilityCode: 'alert.read',
    domain: 'team',
    binding: 'CommercialIntelligenceUseCases.getOperationalAlerts',
    available: true,
    reason: 'AVAILABLE',
  },
  'alert.manage': {
    toolCode: 'team',
    capabilityCode: 'alert.manage',
    domain: 'team',
    binding: 'CoordinatorCommercialAgent.configureAlerts',
    available: true,
    reason: 'AVAILABLE',
  },
  'coaching.read': {
    toolCode: 'team',
    capabilityCode: 'coaching.read',
    domain: 'team',
    binding: 'GamificationService.getWeeklyFeedback',
    available: true,
    reason: 'AVAILABLE',
  },
  'coaching.suggest': {
    toolCode: 'team',
    capabilityCode: 'coaching.suggest',
    domain: 'team',
    binding: 'CommercialIntelligenceAiService.suggestCoaching',
    available: true,
    reason: 'AVAILABLE',
  },
  'coaching.manage': {
    toolCode: 'team',
    capabilityCode: 'coaching.manage',
    domain: 'team',
    binding: 'ManagerCommercialAgent.manageCoachingPlan',
    available: true,
    reason: 'AVAILABLE',
  },
  'goal.read': {
    toolCode: 'team',
    capabilityCode: 'goal.read',
    domain: 'team',
    binding: 'CommercialIntelligenceUseCases.getGoals',
    available: true,
    reason: 'AVAILABLE',
  },
  'goal.manage': {
    toolCode: 'team',
    capabilityCode: 'goal.manage',
    domain: 'team',
    binding: 'ManagerCommercialAgent.updateGoals',
    available: true,
    reason: 'AVAILABLE',
  },
  'performance.read': {
    toolCode: 'team',
    capabilityCode: 'performance.read',
    domain: 'team',
    binding: 'CommercialIntelligenceUseCases.getIndividualPerformance',
    available: true,
    reason: 'AVAILABLE',
  },
  'performance.analyze': {
    toolCode: 'team',
    capabilityCode: 'performance.analyze',
    domain: 'team',
    binding: 'CommercialIntelligenceAiService.analyzeIndividualPerformance',
    available: true,
    reason: 'AVAILABLE',
  },

  // 15. Knowledge & Platform
  'knowledge.search': {
    toolCode: 'knowledge',
    capabilityCode: 'knowledge.search',
    domain: 'knowledge',
    binding: 'KnowledgeService.search',
    available: true,
    reason: 'AVAILABLE',
  },
  'agent.discover': {
    toolCode: 'platform',
    capabilityCode: 'agent.discover',
    domain: 'platform',
    binding: 'AgentCatalogService.listAgentDefinitions',
    available: true,
    reason: 'AVAILABLE',
  },
  'agent.execute': {
    toolCode: 'platform',
    capabilityCode: 'agent.execute',
    domain: 'platform',
    binding: 'CapabilityAuthorizationService.authorize',
    available: true,
    reason: 'AVAILABLE',
  },
  'agent.request_cross_role': {
    toolCode: 'platform',
    capabilityCode: 'agent.request_cross_role',
    domain: 'platform',
    binding: null,
    available: false,
    reason: 'FUTURE_TOOL',
  },
};

export function getToolBinding(capabilityCode: string): ToolBinding | undefined {
  return TOOL_BINDING_REGISTRY[capabilityCode];
}
