// PROMPT 2 — Importação do Arsenal Birth Hub 360.
//
// Dado factual (nomes de agente + bucket de role de origem), transcrito manualmente de
// `scripts/buildDatabase.ts` do pacote ZIP "birthhub360" fornecido pelo usuário (upload de
// 2026-09-08) — não é uma cópia do código-fonte daquele app (React/Vite/Firebase, projeto
// separado), só os dados brutos necessários para a importação governada nesta Central.
//
// Por que o NOME BRUTO (esta lista) e não `src/data/db.ts` daquele pacote: `db.ts` é gerado
// automaticamente a partir destas mesmas listas por `generateDescription`/`determinePriority`/
// `determineActionType` (regras de substring simples sobre o nome) — description/expectedOutcome
// resultam em só ~20 textos únicos repetidos entre os 392 registros (confirmado por inspeção:
// nenhum conteúdo autoral por agente além do nome). Classificar a partir do nome bruto, antes
// dessa geração, é mais honesto e produz sinal melhor do que usar os campos já templados.
//
// Ver também scripts/agent-import/source-prompts.ts — os 29 agentes que SÃO curados com prompt
// real (arquivo `src/data/agents.ts` do mesmo pacote), sobrepostos por nome nesta importação.

export interface SourceRole {
  id: string;
  name: string;
  area: string;
  domain: string;
}

export const sourceRoles: SourceRole[] = [
  {
    id: 'cro-vp-sales',
    name: 'CRO / VP Sales',
    area: 'Prospecção, Vendas e Receita',
    domain: 'Vendas',
  },
  {
    id: 'coo-revops',
    name: 'COO / RevOps',
    area: 'RevOps, Operações e Dados',
    domain: 'Operações',
  },
  {
    id: 'cmo-growth',
    name: 'CMO / Growth',
    area: 'Marketing, Growth e Marca',
    domain: 'Marketing',
  },
  {
    id: 'vp-customer-success',
    name: 'VP Customer Success',
    area: 'Customer Success, Retenção e Expansão',
    domain: 'Customer Success',
  },
  {
    id: 'cfo-finance-ops',
    name: 'CFO / Finance Ops',
    area: 'Financeiro, Billing e Eficiência',
    domain: 'Financeiro',
  },
  {
    id: 'gc-compliance',
    name: 'General Counsel / Compliance Officer',
    area: 'Jurídico, Compliance, Risco e Auditoria',
    domain: 'Compliance/Jurídico',
  },
  {
    id: 'ceo-chief-of-staff',
    name: 'CEO / Chief of Staff',
    area: 'Estratégia Executiva e Board',
    domain: 'Executivo',
  },
  {
    id: 'coo-platform-ops',
    name: 'COO / Platform Ops',
    area: 'Orquestração da Plataforma',
    domain: 'Operações',
  },
  { id: 'ceo', name: 'CEO', area: 'Pack C-Level Executivo', domain: 'Executivo' },
  { id: 'cro', name: 'CRO', area: 'Pack C-Level Receita', domain: 'Vendas' },
  { id: 'coo', name: 'COO', area: 'Pack C-Level Operações', domain: 'Operações' },
  { id: 'cmo', name: 'CMO', area: 'Pack C-Level Marketing', domain: 'Marketing' },
  { id: 'cfo', name: 'CFO', area: 'Pack C-Level Financeiro', domain: 'Financeiro' },
  {
    id: 'compliance-officer',
    name: 'Compliance Officer',
    area: 'Pack Compliance',
    domain: 'Compliance/Jurídico',
  },
  {
    id: 'general-counsel',
    name: 'General Counsel',
    area: 'Pack Jurídico',
    domain: 'Compliance/Jurídico',
  },
  { id: 'cto', name: 'CTO', area: 'Tecnologia', domain: 'Tecnologia' },
  { id: 'head-of-people', name: 'Head of People', area: 'Pessoas e RH', domain: 'RH' },
];

export const croAgents = [
  'Account Manager Bot',
  'Call Review Bot',
  'Closer Copilot Bot',
  'Closing Forecast Bot',
  'Deal Risk Bot',
  'Enablement Coach Bot',
  'Follow-up Bot',
  'Forecast Intelligence Bot',
  'Lead Enrichment Bot',
  'Lead Hunter Bot',
  'Meeting Booker Bot',
  'Objection Handling Bot',
  'Onboarding Sales Bot',
  'Pipeline Auditor Bot',
  'Proposal Bot',
  'Qualification Bot',
  'Roleplay Trainer Bot',
  'SDR Outreach Bot',
  'Sales Agent Pack',
  'Sales Manager Bot',
  'Pipeline Oracle Premium Agent',
  'Pricing Optimizer Premium Agent',
  'Quota Architect Premium Agent',
  'AccountMapper Agent',
  'ActivityAnalyzer Agent',
  'AnnualReportAnalyzer Agent',
  'ArchitectureDiagrammer Agent',
  'CalendarSniper Agent',
  'ColdCallScripter Agent',
  'CompPlanCalculator Agent',
  'CompetitorDisplacement Agent',
  'ContentToLead Agent',
  'ContractDrafter Agent',
  'ConversionForecaster Agent',
  'DataCleaner Agent',
  'DealAtRiskAlerter Agent',
  'DealDeskAutopilot Agent',
  'DeckCustomizer Agent',
  'DemoSandboxer Agent',
  'DemoScripter Agent',
  'DiscountApprover Agent',
  'DiscountLeakGuard Agent',
  'DiscountWaterfallModeler Agent',
  'EarlyAdopterNurturer Agent',
  'EnrichmentBot Agent',
  'EventQualifier Agent',
  'ExecSummaryGenerator Agent',
  'ExecutiveDemoCurator Agent',
  'FastQuoter Agent',
  'FollowUpGhost Agent',
  'ForecastRollup Agent',
  'ForecastingModeler Agent',
  'GamificationMaster Agent',
  'GatekeeperBypass Agent',
  'GhostingPreventer Agent',
  'ICPRefiner Agent',
  'InboundScorer Agent',
  'IntentDecoder Agent',
  'LeadScoringModeler Agent',
  'LeaderboardBroadcaster Agent',
  'MarketExpansionModeler Agent',
  'MultiThreader Agent',
  'MultiYearDealModeller Agent',
  'MutualActionTracker Agent',
  'NicheExplorer Agent',
  'ObjectionCrusher Agent',
  'ObjectionFlashcard Agent',
  'OneOnOnePrep Agent',
  'OrgNav Agent',
  'PartnerEcosystemScout Agent',
  'PersonalizationEngine Agent',
  'PipelineInspector Agent',
  'PipelineOracle Agent',
  'PlaybookCreator Agent',
  'PlaybookGenerator Agent',
  'PoCTracker Agent',
  'PriceDiscountImpact Agent',
  'PricingOptimizer Agent',
  'PricingTester Agent',
  'ProcurementHacker Agent',
  'ProductFeedbackLooper Agent',
  'QuotaArchitect Agent',
  'QuotaAttainmentTracker Agent',
  'QuotaSetter Agent',
  'RFPAutoResponder Agent',
  'ROICalculatorBuilder Agent',
  'ROIScenarioModeler Agent',
  'RampUpAssistant Agent',
  'RepCoach AI Agent',
  'RoutingTrafficCop Agent',
  'SecurityQuestionnaireFiller Agent',
  'StakeholderPersonaGenerator Agent',
  'StrategicAllianceScout Agent',
  'TargetScraper Agent',
  'TechObjectionResolver Agent',
  'TerritoryBalancer Agent',
  'TerritoryMapper Agent',
  'TieringOptimizer Agent',
  'TranscriptCoach Agent',
  'TriggerEventWatcher Agent',
  'UseCaseGenerator Agent',
  'ValueAligner Agent',
  'VerticalTranslator Agent',
  'VoicemailDropper Agent',
  'WebinarNurturer Agent',
  'WinLossAnalyzer Agent',
];

export const cooRevopsAgents = [
  'Admin Ops Bot',
  'CRM Sync Bot',
  'Communication Bot',
  'KPI Analyst Bot',
  'Ops Agent Pack',
  'Productivity Bot',
  'RevOps Intelligence Bot',
  'Culture Pulse Premium Agent',
  'ABTestSynthesizer Agent',
  'ACVGrowthTracker Agent',
  'APIIntegrationBuilder Agent',
  'ARRBridgeBuilder Agent',
  'AnomalyDetector Agent',
  'ApprovalWorkflowRouter Agent',
  'AttributionModeler Agent',
  'AudienceSegmentDiscoverer Agent',
  'BottleneckDetector Agent',
  'CRMCleanser Agent',
  'CampaignDecayPredictor Agent',
  'CapacityPlanner Agent',
  'ChannelAttritionPredictor Agent',
  'ChurnCohortIsolator Agent',
  'CohortAnalyzer Agent',
  'CompetitorFinancialScraper Agent',
  'CompetitorIntelBroadcaster Agent',
  'CulturePulse Agent',
  'CustomCRMUIBuilder Agent',
  'DashboardAutoFreshener Agent',
  'DataCleaningBot Agent',
  'DataEnrichmentAutomator Agent',
  'DataSiloBridger Agent',
  'DuplicateMerger Agent',
  'FeatureHeatmapper Agent',
  'FunnelLeakDetector Agent',
  'GTMAlignmentScorer Agent',
  'GeospatialExpansionMapper Agent',
  'JourneyDropOffLocator Agent',
  'LTVbyChannelCalculator Agent',
  'MacroFactorTracker Agent',
  'Mapeia Agent',
  'MarginCalculator Agent',
  'MarketShareEstimator Agent',
  'MediaMixOptimizer Agent',
  'MicroLearningCreator Agent',
  'NetRetentionModeler Agent',
  'NonStandardFlag Agent',
  'OnboardingRampTracker Agent',
  'PipelineVelocityTracker Agent',
  'PlaybookUpdater Agent',
  'PricingElasticityTester Agent',
  'ProcessBottleneckAlerter Agent',
  'ProcessFlowMapper Agent',
  'RequirementsGatherer Agent',
  'ResourceBalancer Agent',
  'SQLQueryGenerator Agent',
  'ScopeCreepDetector Agent',
  'SessionReplaySummarizer Agent',
  'StakeholderUpdateAutomator Agent',
  'StatSignificanceTester Agent',
  'StickinessTracker Agent',
  'SupplyChainSync Agent',
  'ToolROIAnalyzer Agent',
  'UserStoryWriter Agent',
  'ValidationRuleEnforcer Agent',
  'VoicePitchGrader Agent',
  'WebhookMonitor Agent',
];

export const cmoAgents = [
  'Brand Guardian Premium Agent',
  'Competitor X Ray Premium Agent',
  'ABTestAutomator Agent',
  'ActivationOptimizer Agent',
  'AdCopyMachine Agent',
  'AdFatigueMonitor Agent',
  'AgencyAuditor Agent',
  'BacklinkScouter Agent',
  'BattlecardUpdater Agent',
  'BidAutoAdjuster Agent',
  'BrandGuardian Agent',
  'BrandGuidelineEnforcer Agent',
  'CACLTVModeler Agent',
  'CampaignOrchestrator Agent',
  'CannibalizationDetector Agent',
  'ChannelMixer Agent',
  'ChurnWinBackSequencer Agent',
  'CompetitorX-Ray Agent',
  'ContentRepurposer Agent',
  'CreativeAssetTester Agent',
  'CrisisCommsDrafter Agent',
  'DashboardAutomator Agent',
  'DataHygieneMonitor Agent',
  'DistributionAutomator Agent',
  'DripCampaignTrigger Agent',
  'GlobalBrandLocalizer Agent',
  'InfluencerVettor Agent',
  'KeywordOpportunitySpotter Agent',
  'LandingPageMorpher Agent',
  'LaunchPlanner Agent',
  'LeadMagnetCreator Agent',
  'LeadRoutingTroubleshooter Agent',
  'MarTechSync Agent',
  'MarketingTechArchitect Agent',
  'NewsletterCurator Agent',
  'OnPageOptimizer Agent',
  'PRScraper Agent',
  'PersonaSync Agent',
  'PlagiarismToneChecker Agent',
  'PositioningTester Agent',
  'ROASMaximizer Agent',
  'ReleaseNoteWriter Agent',
  'SEODraftWriter Agent',
  'SERPVolatilityTracker Agent',
  'SchemaMarkupGenerator Agent',
  'SentimentShiftAlerter Agent',
  'SubjectLineTester Agent',
  'TopicClusterPlanner Agent',
  'UTMBuilderBot Agent',
  'UnsubscribePredictor Agent',
  'ViralLoopTracker Agent',
  'WebinarPromoter Agent',
];

export const vpCsAgents = [
  'Customer Health Bot',
  'Customer Success Agent Pack',
  'Churn Deflector Premium Agent',
  'Expansion Mapper Premium Agent',
  'APIKeyConfigurator Agent',
  'AdoptionMetricAnalyzer Agent',
  'AdvocacyFinder Agent',
  'AhaMomentTracker Agent',
  'AngryCustomerEscalator Agent',
  'BestPracticeRecommender Agent',
  'CSATNPSAggregator Agent',
  'ChurnDeflector Agent',
  'CrossSellMapper Agent',
  'CustomScriptGenerator Agent',
  'DataMigrationValidator Agent',
  'DelayEscalator Agent',
  'EscalationPredictor Agent',
  'ExecutiveSponsorTracker Agent',
  'ExpansionMapper Agent',
  'FAQAutoResponder Agent',
  'HealthScoreArchitect Agent',
  'HealthScoreTrigger Agent',
  'JourneyArchitect Agent',
  'KBGapIdentifier Agent',
  'L1AutoResolver Agent',
  'L3BugReplicator Agent',
  'MilestoneChaser Agent',
  'OutageCommunicator Agent',
  'PatchUpdateAlerter Agent',
  'PricingTierRecommender Agent',
  'ProjectPlanTracker Agent',
  'QBRDeckBuilder Agent',
  'RefundProcessor Agent',
  'RelationshipMatrixBuilder Agent',
  'RenewalContractGenerator Agent',
  'RenewalForecastEngine Agent',
  'SLAMonitor Agent',
  'ScalabilityPredictor Agent',
  'SemanticSearchKB Agent',
  'SentimentAggregator Agent',
  'ShiftScheduler Agent',
  'TicketBacklogAnalyzer Agent',
  'TicketClassifier Agent',
  'TrainingVideoRecommender Agent',
  'UpsellPrompt Agent',
  'VIPConcierge Agent',
  'WelcomeSequencer Agent',
  'WhiteSpaceAnalyzer Agent',
];

export const cfoAgents = [
  'Finance Agent Pack',
  'Budget Fluid Premium Agent',
  'AccrualEngine Agent',
  'AgingReportSender Agent',
  'AuditTrailBuilder Agent',
  'BadDebtPredictor Agent',
  'BankReconciliationBot Agent',
  'BankruptcyRiskMonitor Agent',
  'BudgetFluid Agent',
  'BudgetVariancePinger Agent',
  'BurnRateMonitor Agent',
  'CapTableManager Agent',
  'CashAppMatcher Agent',
  'CashFlowClairvoyant Agent',
  'CloudSpendOptimizer Agent',
  'CollectionAgencyRouter Agent',
  'ComplianceChecklistEnforcer Agent',
  'ContractRedliner Agent',
  'CreditHoldReleaser Agent',
  'CreditLimitRecommender Agent',
  'CreditScoreFetcher Agent',
  'DisputedChargeAggregator Agent',
  'DunningAutomator Agent',
  'FXRiskManager Agent',
  'FailedPaymentRetrier Agent',
  'FinancialRatioCalculator Agent',
  'GLAnomalyDetector Agent',
  'IPInfringementScraper Agent',
  'InstanceRightSizer Agent',
  'InvoiceGenerator Agent',
  'MonthEndCloseAutomator Agent',
  'MultiCloudCostModeler Agent',
  'NDAAutoSigner Agent',
  'PaymentLinkSender Agent',
  'PaymentPlanNegotiator Agent',
  'PromiseToPayTracker Agent',
  'ProrationCalculator Agent',
  'RegulatoryChangeAlerter Agent',
  'RemittanceExtractor Agent',
  'RiskExposureQuantifier Agent',
  'SpendController Agent',
  'TaxExemptionVerifier Agent',
  'TaxOptimizer Agent',
  'TradeReferenceChecker Agent',
  'VendorNegotiator Agent',
];

export const gcAgents = [
  'AccessRightAuditor Agent',
  'AddressProofValidator Agent',
  'AltDataScorer Agent',
  'AuditBot Agent',
  'AuditPrepEngine Agent',
  'AutoDecisionEngine Agent',
  'CapacityModeler Agent',
  'CapitalAdequacyCalculator Agent',
  'CentralBankXMLGenerator Agent',
  'ChargebackDisputeAutomator Agent',
  'CommsSurveillanceBot Agent',
  'ComplianceEnforcer Agent',
  'CryptoTracingBot Agent',
  'DeadlineTracker Agent',
  'DefaultProbabilityModeler Agent',
  'DeviceFingerprintMatcher Agent',
  'FalsePositiveReducer Agent',
  'HighRiskJurisdictionPinger Agent',
  'IDVerificationMatcher Agent',
  'IncidentPostMortemDrafter Agent',
  'LegalClauseMatcher Agent',
  'LimitDecreaseRecommender Agent',
  'LiquidityRatioMonitor Agent',
  'LivenessCheckAnalyzer Agent',
  'MoneyMuleDetector Agent',
  'PEPScreener Agent',
  'PolicyMappingBot Agent',
  'ProcessWalkthroughAutomator Agent',
  'ProcurementPolicyBot Agent',
  'RegulatoryTrainingTracker Agent',
  'RemediationPlanTracker Agent',
  'SARDrafter Agent',
  'SLAEscalator Agent',
  'SaaSLicenseAuditor Agent',
  'SanctionsScreener Agent',
  'StressTestModeler Agent',
  'SyntheticIdentityDetector Agent',
  'TechStackAuditor Agent',
  'TransactionHoldReviewer Agent',
  'TransactionLinkAnalyzer Agent',
  'UBOMapper Agent',
  'VelocityRuleEngine Agent',
];

export const ceoChiefOfStaffAgents = [
  'Board Prep AI Premium Agent',
  'Capital Allocator Premium Agent',
  'Crisis Navigator Premium Agent',
  'Market Sentinel Premium Agent',
  'Narrative Weaver Premium Agent',
  'Trend Catcher Premium Agent',
  'BoardPrep AI Agent',
  'BoardReportingAutomator Agent',
  'CapitalAllocator Agent',
  'CrisisNavigator Agent',
  'ExecutiveSummaryBot Agent',
  'MarketSentinel Agent',
  'NarrativeWeaver Agent',
  'ScenarioModeler Agent',
  'StrategicKPIAggregator Agent',
  'StrategicPartnerScout Agent',
  'TrendCatcher Agent',
];

export const cooPlatformOpsAgents = [
  'Agent Mesh Orchestrator',
  'Context Memory Bot',
  'Knowledge Bot',
  'Maestro Orchestrator',
  'Implementer Agent',
  'Planner Agent',
  'Reviewer Agent',
];

export const singletonAgents: { roleId: string; name: string }[] = [
  { roleId: 'ceo', name: 'CEO Agent Pack' },
  { roleId: 'cro', name: 'CRO Agent Pack' },
  { roleId: 'coo', name: 'COO Agent Pack' },
  { roleId: 'cmo', name: 'CMO Agent Pack' },
  { roleId: 'cfo', name: 'CFO Agent Pack' },
  { roleId: 'compliance-officer', name: 'Policy & Approval Guard' },
  { roleId: 'general-counsel', name: 'Legal Agent Pack' },
  { roleId: 'cto', name: 'CTO Agent Pack' },
  { roleId: 'head-of-people', name: 'RH Agent Pack' },
];

export const ALL_BUCKETS: { roleId: string; names: string[] }[] = [
  { roleId: 'cro-vp-sales', names: croAgents },
  { roleId: 'coo-revops', names: cooRevopsAgents },
  { roleId: 'cmo-growth', names: cmoAgents },
  { roleId: 'vp-customer-success', names: vpCsAgents },
  { roleId: 'cfo-finance-ops', names: cfoAgents },
  { roleId: 'gc-compliance', names: gcAgents },
  { roleId: 'ceo-chief-of-staff', names: ceoChiefOfStaffAgents },
  { roleId: 'coo-platform-ops', names: cooPlatformOpsAgents },
  ...singletonAgents.map((s) => ({ roleId: s.roleId, names: [s.name] })),
];
