import fs from 'node:fs';
import { ROOT, REPO, A, VPS, esc, img, code, codeFrom, table, kv, badge, rgbToHex, lines, excerpt, exists, crop, defBlock } from './lib.mjs';
import { stateBlock } from './chB.mjs';
const link = (n) => `<a href="#comp/${n}">${n}</a>`;
const grepFiles = (rx, dir = `${REPO}/src`, exts = /\.(tsx|ts|css)$/) => { const out = []; const walk = (d) => { for (const f of fs.readdirSync(d, { withFileTypes: true })) { const p = `${d}/${f.name}`; if (f.isDirectory()) { if (f.name !== 'node_modules') walk(p); } else if (exts.test(f.name)) { fs.readFileSync(p, 'utf8').split('\n').forEach((l, i) => { if (rx.test(l)) out.push({ file: p.replace(REPO + '/', ''), line: i + 1, text: l.trim() }); }); } } }; walk(dir); return out; };

export function icons(ctx) {
  const I = ctx.icons; const compFor = (files) => [...new Set(files.flatMap((f) => (ctx.compsInFile[f] || []).slice(0, 2)))].slice(0, 3);
  const cards = I.custom.map((c) => `<div class="icard" data-q="${esc(c.name + ' ' + c.file)}"><div class="iprev">${c.svg}</div><b>${esc(c.name)}</b><small><code>${c.file.split('/').pop()}${c.line ? ':' + c.line[0] : ''}</code></small><small>viewBox <code>${c.viewBox || '—'}</code> · stroke <code>${c.stroke || '—'}</code> · fill <code>${c.fill || '—'}</code></small><small>usos: ${c.uses}${c.ariaHidden ? ' · aria-hidden' : ''}</small><details><summary>SVG / código</summary>${code(c.file, c.line?.[0], c.line?.[1], c.code || c.svg, 'tsx', 'definição')}${code(null, 0, 0, c.svg, 'svg', 'SVG renderizado')}<p>Usado em: ${c.usedIn.map((u) => `<code>${u[0]}</code>×${u[1]}`).join(', ') || '—'}<br>Componentes: ${compFor(c.usedIn.map((u) => u[0])).map(link).join(', ') || '—'}</p></details></div>`).join('');
  const lu = I.lucide.map((c) => `<div class="icard small" data-q="${esc(c.name)}"><div class="iprev">${c.svg}</div><b>${esc(c.name)}</b><small>${c.importedIn} arquivo(s)</small></div>`).join('');
  const rt = {}; for (const r of ctx.routes) for (const s of ctx.shots[r][1440]?.svgs || []) { const m = (s.cls || '').match(/lucide-([\w-]+)/); const k = m ? 'lucide:' + m[1] : 'custom'; (rt[k] = rt[k] || { n: 0, routes: {} }).n++; rt[k].routes[r] = 1; }
  const inl = I.inline.map((s) => `<div class="item"><code>${s.file}:${s.line[0]}-${s.line[1]}</code>${code(s.file, s.line[0], s.line[1], s.code, 'tsx')}</div>`).join('');
  const sizes = {}; for (const r of ctx.routes) for (const s of ctx.shots[r][1440]?.svgs || []) { const k = `${s.w}×${s.h}`; sizes[k] = (sizes[k] || 0) + 1; }
  const ov = I.custom.filter((c) => c.name.startsWith('Icon')).map((c) => { const base = c.name.slice(4); const hit = I.lucide.find((l) => l.name === base || l.name.toLowerCase() === base.toLowerCase()); return hit ? [`<div class="iprev sm">${c.svg}</div>`, c.name, `<div class="iprev sm">${hit.svg}</div>`, hit.name, c.uses, hit.importedIn] : null; }).filter(Boolean);
  return `<h1>Icons</h1><p>Três fontes reais: <b>${I.custom.length}</b> ícones próprios (<code>src/components/icons/BrandIcons.tsx</code>, <code>HubIcons.tsx</code>, <code>ui/icons/*</code>), <b>${I.lucide.length}</b> ícones <code>lucide-react</code> v${I.lucideVersion} importados em ${new Set(I.lucide.flatMap((l) => l.files)).size}+ arquivos, e <b>${I.inline.length}</b> blocos <code>&lt;svg&gt;</code> inline em componentes. Todos renderizados abaixo com <code>react-dom/server</code> a partir dos componentes reais.</p>
<input class="tfilter" id="iconfilter" placeholder="buscar ícone…" aria-label="Buscar ícone"><h2>Ícones próprios</h2><div class="igrid">${cards}</div><h2>lucide-react (usados)</h2><div class="igrid">${lu}</div>
<h2>SVG inline em componentes</h2>${inl}<h2>Tamanhos renderizados (DOM)</h2>${table(['w×h (px)', 'Ocorrências'], Object.entries(sizes).sort((a, b) => b[1] - a[1]).slice(0, 12).map(([k, v]) => [k, v]))}
<h2>Equivalentes duplicados (própria × lucide)</h2>${ov.length ? table(['Próprio', 'Nome', 'lucide', 'Nome', 'Usos próprio', 'Arquivos lucide'], ov) : '<p>Nenhum par com nome equivalente.</p>'}`;
}
export function modals(ctx) {
  const ovs = ctx.states.overlays.map((o) => `<div class="item"><h4>${esc(o.name)}</h4>${o.err ? `<p class="bad">não capturado: ${esc(o.err)}</p>` : (exists(`${ROOT}/states/overlay-${o.name}.png`) ? img(`states/overlay-${o.name}.png`, o.name) : '')}${o.info ? kv({ role: o.info.role, tag: o.info.tag, background: o.info.bg, 'border-radius': o.info.radius, 'box-shadow': o.info.shadow, 'z-index': o.info.z, 'backdrop-filter': o.info.backdrop, tamanho: `${Math.round(o.info.rect.w)}×${Math.round(o.info.rect.h)}` }) + code(null, 0, 0, o.info.html, 'html', 'HTML real') : '<p>Nenhum <code>role=dialog/menu/listbox</code> detectado ao abrir — ver screenshot.</p>'}</div>`).join('');
  const defs = ['Dialog', 'Drawer', 'BottomSheet', 'ConfirmDialog', 'CommandPalette', 'ContextualTip', 'AIContextPopover', 'ToolTechPopover'].filter((n) => ctx.compindex[n]).map((n) => { const d = ctx.primaryDef(n); const b = defBlock(d.file, d.line, 45); return `<h3>${n}</h3><p><code>${d.file}:${d.line}</code> · ${ctx.routesByComp[n] ? 'renderizado em ' + ctx.routesByComp[n].length + ' tela(s)' : 'só existe quando aberto'}</p>${code(d.file, b.start, b.end, b.code)}`; }).join('');
  return `<h1>Modals, drawers, popovers</h1><h2>Capturados abertos no navegador</h2>${ovs || '<p>Nenhum overlay capturado.</p>'}<h2>Primitivos (código real)</h2>${defs}`;
}
export function feedback(ctx) {
  const def = ['EmptyState', 'Skeleton', 'Toaster', 'Badge', 'BlockedState', 'ErrorBoundary', 'PageFallback'].filter((n) => ctx.compindex[n]).map((n) => { const d = ctx.primaryDef(n); const b = defBlock(d.file, d.line, 40); return `<div class="item"><h4><a href="#comp/${n}">${n}</a></h4><p><code>${d.file}:${d.line}</code> · ${ctx.routesByComp[n] ? `visível em ${ctx.routesByComp[n].length} tela(s): ${ctx.routesByComp[n].slice(0, 6).map((r) => `<a href="#screen/${r}"><code>${r}</code></a>`).join(' ')}` : 'não visível nas telas percorridas'}</p>${ctx.compshots[n] ? img(ctx.compshots[n].shot, n) : ''}${code(d.file, b.start, b.end, b.code)}</div>`; }).join('');
  const nf = ctx.shots['/rota-inexistente-404']?.[1440];
  const nfx = nf ? `<h2>Rota inexistente</h2><p><code>/rota-inexistente-404</code> resolveu para <code>${esc(nf.finalUrl.replace('http://localhost:3024', ''))}</code> — o catch-all <code>&lt;Route path="*"&gt;</code> redireciona; não existe tela 404 dedicada.</p>${img(nf.screenshot, '404')}` : '';
  const bk = ctx.shots['/book/demo']?.[1440];
  return `<h1>Feedback</h1><p>Empty, loading, erro e toasts. Com o banco vazio, os estados vazios são o comportamento real capturado.</p>${nfx}${bk ? `<h2>Página pública com slug inexistente (<code>/book/demo</code>)</h2>${img(bk.screenshot, 'book demo')}` : ''}${exists(`${ROOT}/states/login-error-email-invalido.png`) ? `<h2>Erro de validação (login)</h2>${img('states/login-error-email-invalido.png', 'erro login')}` : ''}<h2>Componentes</h2>${def}`;
}
export function statesCh(ctx) {
  const ok = ctx.states.states.filter((s) => s.ok).map((s) => stateBlock(ctx, s)).join(''); const bad = ctx.states.states.filter((s) => !s.ok).map((s) => `<li><code>${esc(s.name)}</code>: ${esc(s.err)}</li>`).join('');
  const dis = []; for (const r of ctx.routes) for (const g of ctx.shots[r][1440]?.groups?.button || []) { const s = g.samples[0]; if (s?.disabled) dis.push([`<code>${esc(r)}</code>`, esc(s.text), `<code>${esc(s.styles.opacity)}</code>`, `<code>${esc(s.styles.backgroundColor)}</code>`, s.shot ? img(s.shot, s.text) : '']); }
  return `<h1>States</h1><p>Hover, focus (teclado), active e default de componentes reais, com screenshot de cada estado e a diferença de estilo computado lida do navegador.</p>${ok || '<p>Não capturado.</p>'}${bad ? `<h3>Alvos que falharam</h3><ul>${bad}</ul>` : ''}<h2>Disabled encontrados</h2>${dis.length ? table(['Rota', 'Texto', 'opacity', 'background', 'Screenshot'], dis) : '<p>Nenhum botão desabilitado visível nas telas percorridas (estado vazio).</p>'}<p>Notas de execução: ${ctx.states.notes.map(esc).join(' · ') || '—'}</p>`;
}
export function responsive(ctx) {
  const rows = ctx.routes.map((r) => [`<a href="#screen/${r}"><code>${esc(r)}</code></a>`, ...VPS.map(([w]) => { const d = ctx.shots[r]?.[w]; return d ? (d.hOverflow ? `<span class="bad">overflow ${d.scroll.docW}px</span>` : `<span class="ok">ok</span>`) + `<br><small>toque&lt;44: ${d.touch.small}/${d.touch.total}</small>` : '—'; })]);
  const over = ctx.routes.filter((r) => VPS.some(([w]) => ctx.shots[r]?.[w]?.hOverflow));
  const ovDetail = over.slice(0, 10).map((r) => { const w = VPS.map((v) => v[0]).find((w) => ctx.shots[r]?.[w]?.hOverflow); const d = ctx.shots[r][w]; return `<div class="item"><h4><code>${esc(r)}</code> @ ${w}px</h4><p>scrollWidth ${d.scroll.docW}px &gt; viewport ${d.viewport.w}px. Elementos que ultrapassam: ${d.overflowers.map((o) => `<code>&lt;${o.tag} class="${esc(o.cls.slice(0, 60))}"&gt;</code> (right ${o.right})`).join(', ') || '—'}</p>${img(d.screenshot, r)}</div>`; }).join('');
  const nav = VPS.map(([w, h]) => { const d = ctx.shots['/app']?.[w]; return d ? `<figure class="vp"><figcaption>/app · ${w}×${h}</figcaption>${img(d.screenshot, '/app ' + w)}</figure>` : ''; }).join('');
  return `<h1>Responsive</h1><p>Cada rota foi renderizada em ${VPS.length} viewports (1440, 1280, 1024, 768, 430, 390, 375; abaixo de 768px com emulação mobile/touch). Matriz de overflow horizontal e alvos de toque &lt; 44px, medidos no DOM:</p>${table(['Rota', ...VPS.map(([w]) => w)], rows, { filter: true })}
<h2>Layout da casca em todos os viewports (<code>/app</code>)</h2><div class="vps">${nav}</div><h2>Telas com overflow horizontal (${over.length})</h2>${ovDetail || '<p>Nenhuma.</p>'}`;
}
export function a11y(ctx) {
  const items = []; const noName = [], noLabel = [], multiH1 = [], noMain = [], small = [];
  for (const r of ctx.routes) { const d = ctx.shots[r][1440]; if (!d?.a11y) continue; for (const b of d.a11y.btnNoName) noName.push({ r, ...b, d }); for (const i of d.a11y.inputNoLabel) noLabel.push({ r, ...i, d }); if (d.a11y.h1Count > 1) multiH1.push({ r, n: d.a11y.h1Count, d }); if (d.a11y.landmarkMain !== 1) noMain.push({ r, n: d.a11y.landmarkMain }); const m = ctx.shots[r][390]; if (m) small.push([`<a href="#screen/${r}"><code>${esc(r)}</code></a>`, m.touch.small, m.touch.total, `${Math.round((100 * m.touch.small) / Math.max(1, m.touch.total))}%`]); }
  const ev = (arr, title, imp, fix) => `<h3>${title} (${arr.length})</h3><p><b>Impacto:</b> ${imp}<br><b>Correção sugerida:</b> ${fix}</p>${arr.slice(0, 6).map((x) => `<div class="item"><p><code>${esc(x.r)}</code></p>${x.rect ? crop(x.d.screenshot, x.rect, x.d.viewport.w, x.d.viewport.h, { maxW: 360 }) : ''}${code(null, 0, 0, x.html || `${x.n} ocorrências`, 'html', 'HTML real do elemento')}</div>`).join('')}`;
  const focus = ctx.states.states.filter((s) => s.ok).map((s) => [`<code>${esc(s.name)}</code>`, `<code>${esc(s.states.focus?.outlineStyle)} ${esc(s.states.focus?.outlineWidth)} ${esc(s.states.focus?.outlineColor)}</code>`, `<code>${esc(s.states.focus?.boxShadow?.slice(0, 70))}</code>`, exists(`${ROOT}/states/${s.name}__focus.png`) ? img(`states/${s.name}__focus.png`, 'focus') : '']);
  const rm = grepFiles(/prefers-reduced-motion|useReducedMotion|MotionConfig/); const rmFiles = [...new Set(rm.map((x) => x.file))];
  const anim = grepFiles(/repeat:\s*Infinity|animate-(pulse|spin|ping|bounce)/); const animFiles = [...new Set(anim.map((x) => x.file))];
  const esl = lines('eslint.config.mjs').map((l, i) => ({ l, i })).filter((x) => /jsx-a11y\/[\w-]+/.test(x.l)).slice(0, 30);
  return `<h1>Accessibility</h1><p>Achados medidos no DOM real de cada tela (1440px) + configuração de lint. Cada problema abaixo traz recorte do screenshot, HTML real, impacto e correção sugerida.</p>
${ev(noName, 'Botões sem nome acessível', 'leitores de tela anunciam apenas “botão”', 'adicionar <code>aria-label</code> ou texto visível oculto (<code>sr-only</code>)')}${ev(noLabel, 'Inputs sem label associado', 'campo sem rótulo programático (WCAG 1.3.1 / 4.1.2)', 'associar <code>&lt;label htmlFor&gt;</code> ou <code>aria-label</code>')}${ev(multiH1, 'Telas com mais de um &lt;h1&gt;', 'hierarquia de headings ambígua para navegação por título', 'manter um único h1 por tela; demais como h2/h3 ou &lt;p&gt;')}
<h3>Telas sem exatamente um landmark &lt;main&gt; (${noMain.length})</h3><p>${noMain.map((x) => `<code>${esc(x.r)}</code> (${x.n})`).join(', ') || 'nenhuma'}</p>
<h2>Foco visível (teclado)</h2>${table(['Componente', 'outline', 'box-shadow', 'Screenshot'], focus)}
<h2>Alvos de toque em 390×844</h2><p>Botões/links visíveis com largura ou altura &lt; 44px (recomendação WCAG 2.5.5 / Material 48dp). O app roda em Android via Capacitor.</p>${table(['Rota', '&lt;44px', 'Total', '%'], small, { filter: true })}
<h2>Movimento reduzido</h2><p>${rmFiles.length} arquivos referenciam <code>prefers-reduced-motion</code>/<code>useReducedMotion</code>/<code>MotionConfig</code>; ${animFiles.length} arquivos têm animação em loop (<code>repeat: Infinity</code> ou <code>animate-pulse/spin/ping/bounce</code>).</p>${table(['Arquivo:linha', 'Trecho'], rm.slice(0, 12).map((x) => [`<code>${x.file}:${x.line}</code>`, `<code>${esc(x.text.slice(0, 110))}</code>`]))}
<h2>Regras jsx-a11y no ESLint</h2>${esl.length ? code('eslint.config.mjs', esl[0].i + 1, esl[esl.length - 1].i + 1, esl.map((x) => x.l).join('\n'), 'js') : '<p>—</p>'}`;
}
export function motion(ctx) {
  const kf = ctx.tokens.keyframes.map((k) => `<div class="item"><h4><code>@keyframes ${k.name}</code> <small>src/styles/globals.css:${k.line}</small></h4>${codeFrom('src/styles/globals.css', k.line, Math.min(k.line + 9, lines('src/styles/globals.css').length), 'css')}</div>`).join('');
  const inf = grepFiles(/repeat:\s*Infinity/).slice(0, 25);
  const anim = ctx.tokens.tokens.filter((t) => t.group === 'motion');
  const lib = lines('src/lib/motion.ts').length ? codeFrom('src/lib/motion.ts', 1, Math.min(60, lines('src/lib/motion.ts').length), 'ts', 'variantes/easings padronizados') : '';
  return `<h1>Motion</h1><p>Biblioteca padrão: Framer Motion (<code>src/lib/motion.ts</code>). Tokens de movimento em <code>@theme</code>: ${anim.map((t) => `<code>${t.name}</code>`).join(', ') || '—'}.</p>${lib}<h2>Keyframes CSS (${ctx.tokens.keyframes.length})</h2>${kf}<h2>Loops infinitos em código (${inf.length}+)</h2>${table(['Arquivo:linha', 'Código'], inf.map((x) => [`<code>${x.file}:${x.line}</code>`, `<code>${esc(x.text.slice(0, 120))}</code>`]))}`;
}
export function consistency(ctx) {
  const out = []; const item = (t, body) => out.push(`<div class="item issue"><h3>${t}</h3>${body}</div>`);
  const d0 = ctx.shots['/app']?.[1440];
  // 1 fontes
  const h1 = ctx.aggList('heading').find((g) => /Playfair/.test(g.sample?.styles.fontFamily || ''));
  item('Fontes reais divergem da constituição (Sora/Inter)', `<p>O <code>CLAUDE.md</code> afirma Sora (display) + Inter (interface) sem CDN. O navegador mediu <b>${[...new Set(ctx.typoList.map((t) => t.key.split('|')[0].split(',')[0].replace(/"/g, '')))].slice(0, 6).join(', ')}</b>. O CSS importa Playfair Display do Google Fonts (<code>globals.css:10</code>), contrariando “nenhuma requisição a CDN de fonte”.</p>${h1?.sample?.shot ? img(h1.sample.shot, 'h1 Playfair') : ''}<p>Medido: <code>${h1?.sample?.styles.fontFamily}</code> ${h1?.sample?.styles.fontSize} em <code>${h1?.route}</code> (componentes: ${(h1?.sample?.comps || []).slice(0, 3).join(' › ')}).</p>${codeFrom('src/styles/globals.css', 10, 20, 'css')}`);
  // 2 botões
  const bl = ctx.aggList('button'); const hs = {}; for (const g of bl) { const h = g.sample?.rect.height; if (h) (hs[h] = hs[h] || []).push(g); }
  const hRows = Object.entries(hs).sort((a, b) => b[1].reduce((x, g) => x + g.count, 0) - a[1].reduce((x, g) => x + g.count, 0)).slice(0, 10).map(([h, gs]) => [h + 'px', gs.reduce((x, g) => x + g.count, 0), [...new Set(gs.map((g) => g.sample.styles.borderRadius))].join(' / '), gs[0].sample.shot ? img(gs[0].sample.shot, 'botão') : '']);
  item('Botões: alturas e radius divergentes para o mesmo papel', `<p>${Object.keys(hs).length} alturas distintas e ${new Set(bl.map((g) => g.sample?.styles.borderRadius)).size} valores de <code>border-radius</code> entre botões visíveis.</p>${table(['Altura', 'Botões', 'radius usados', 'Exemplo'], hRows)}`);
  // 3 radius
  item('Escala de radius sem padrão único', `<p>Valores de <code>border-top-left-radius</code> encontrados no DOM (todas as telas):</p>${table(['radius', 'Elementos', 'Telas'], ctx.radius.slice(0, 14).map((r) => [`<code>${r.value}</code>`, r.count, r.routes]))}<p>Tokens declarados: ${ctx.tokens.tokens.filter((t) => t.group === 'radius').map((t) => `<code>${t.name}=${Object.values(t.values)[0]}</code>`).join(', ') || 'nenhum'}.</p>`);
  // 4 duplicatas
  const dup = [['Button', 'NeonButton'], ['Input', 'CyberInput'], ['Card', 'HolographicCard', 'TiltCard', 'KpiCard'], ['Dialog', 'ConfirmDialog', 'BottomSheet', 'Drawer']].map((g) => g.filter((n) => ctx.compindex[n])).filter((g) => g.length > 1);
  item('Componentes com papel equivalente', dup.map((g) => `<p>${g.map((n) => `<a href="#comp/${n}">${n}</a> (<code>${ctx.primaryDef(n).file}</code>${ctx.routesByComp[n] ? ', ' + ctx.routesByComp[n].length + ' telas' : ', não renderizado nas telas percorridas'})`).join(' · ')}</p><div class="row">${g.map((n) => (ctx.compshots[n] ? `<figure><figcaption>${n}</figcaption>${img(ctx.compshots[n].shot, n)}</figure>` : '')).join('')}</div>`).join(''));
  // 5 hex
  const hx = ctx.tokens.hardcodedHex.slice(0, 8); const ex = hx.slice(0, 5).map((h) => { const f = h.files[0][0]; const L = lines(f); const i = L.findIndex((l) => l.toUpperCase().includes(h.value)); return `<p><i class="sw" style="background:${h.value}"></i> <code>${h.value}</code> ×${h.count}</p>${i >= 0 ? codeFrom(f, i + 1, i + 1, 'tsx') : ''}`; }).join('');
  item(`Cores hex digitadas fora dos tokens (${ctx.tokens.hexDistinct} distintas)`, ex);
  const tw = ctx.tokens.twDefaultPalette.slice(0, 4).map((h) => { const f = h.files[0][0]; const L = lines(f); const i = L.findIndex((l) => l.includes(h.value)); return `<p><code>${h.value}</code> ×${h.count}</p>${i >= 0 ? codeFrom(f, i + 1, i + 1, 'tsx') : ''}`; }).join('');
  item(`Paleta padrão do Tailwind em vez de tokens (${ctx.tokens.twDistinct} classes)`, tw);
  // 6 unused tokens
  const unused = ctx.tokens.tokens.filter((t) => t.uses === 0); item(`Tokens declarados sem nenhum uso em src/ (${unused.length} de ${ctx.tokens.tokens.length})`, `<p>${unused.slice(0, 60).map((t) => `<code>${t.name}</code>`).join(' ')}${unused.length > 60 ? ' …' : ''}</p><p><small>A contagem procura <code>var(--token)</code> e a utilidade Tailwind equivalente; usos dinâmicos (template strings) não são detectados.</small></p>`);
  // 7 múltiplos h1
  const m = ctx.routes.filter((r) => ctx.shots[r][1440]?.a11y?.h1Count > 1).slice(0, 6); item(`Mais de um &lt;h1&gt; por tela (${ctx.routes.filter((r) => ctx.shots[r][1440]?.a11y?.h1Count > 1).length} telas)`, m.map((r) => { const d = ctx.shots[r][1440]; return `<p><code>${esc(r)}</code>: ${d.a11y.h1Count} h1 — ${d.h1.map((t) => `“${esc(t)}”`).join(', ')}</p>`; }).join(''));
  // 8 ícones
  item('Ícones duplicados: própria × lucide', `<p>Veja o par-a-par em <a href="#icons">Icons</a>. ${ctx.icons.custom.filter((c) => c.uses === 0).length} dos ${ctx.icons.custom.length} ícones próprios têm 0 usos fora do arquivo de definição.</p>`);
  return `<h1>Consistency Audit</h1><p>Cada inconsistência abaixo foi verificada com medição no DOM e/ou grep em <code>src/</code>; quando há evidência visual, ela é o screenshot real.</p>${out.join('')}`;
}
export function routeMatrix(ctx) {
  const rows = ctx.pubFirst.map((r) => { const d = ctx.shots[r][1440]; const rc = ctx.rootFor(r); const def = rc.comp ? ctx.primaryDef(rc.comp) : null; const redirected = d.finalUrl.replace('http://localhost:3024', '') !== r; return [`<a href="#screen/${r}"><code>${esc(r)}</code></a>${redirected ? ` <small>→ ${esc(d.finalUrl.replace('http://localhost:3024', ''))}</small>` : ''}`, esc(d.h1?.[0] || d.title), rc.comp ? `${link(rc.comp)} <small>${def ? def.file : ''}</small>` : '—', `<a href="#screen/${r}">${img(d.screenshot, r, 'thumb')}</a>`, ...[1440, 1024, 390].map((w) => (ctx.shots[r][w] ? `<a href="${A}/${ctx.shots[r][w].screenshot}" class="zoomlink">${w}</a>` : '—'))]; });
  const matrix = ctx.pubFirst.map((r) => [`<code>${esc(r)}</code>`, (ctx.compsByRoute[r] || []).length, (ctx.compsByRoute[r] || []).map(link).join(' ')]);
  return `<h1>Route Matrix</h1><h2>Inventário de telas</h2><p>Uma tela só entra se foi renderizada pelo navegador numa rota real de <code>App.tsx</code>. A coluna “Componente raiz” vem do elemento declarado na <code>&lt;Route&gt;</code>.</p>${table(['Rota', 'Título (h1)', 'Componente raiz', 'Screenshot', 'Desktop', 'Tablet', 'Mobile'], rows, { filter: true })}<h2>TELA → COMPONENTES</h2>${table(['Tela', 'Nº', 'Componentes'], matrix, { filter: true })}
<h2>Páginas de tela</h2><p class="chips">${ctx.pubFirst.map((r) => `<a href="#screen/${r}"><code>${esc(r)}</code></a>`).join(' ')}</p>`;
}
export function matrices(ctx) {
  const comps = Object.keys(ctx.routesByComp).sort();
  const c2s = comps.map((c) => [link(c), ctx.routesByComp[c].length, ctx.routesByComp[c].slice(0, 8).map((r) => `<a href="#screen/${r}"><code>${esc(r)}</code></a>`).join(' ') + (ctx.routesByComp[c].length > 8 ? ' …' : '')]);
  const c2f = comps.map((c) => { const d = ctx.primaryDef(c); return [link(c), `<code>${d.file}:${d.line}</code>`, ctx.compindex[c].length > 1 ? ctx.compindex[c].length + ' definições' : '']; });
  const t2c = ctx.tokens.tokens.filter((t) => t.uses > 0).map((t) => [`<code>${t.name}</code>`, t.uses, [...new Set(t.usedIn.flatMap((u) => (ctx.compsInFile[u[0]] || []).slice(0, 3)))].slice(0, 8).map(link).join(', ') || t.usedIn.map((u) => `<code>${u[0]}</code>`).slice(0, 3).join(', ')]);
  const s2c = ctx.icons.custom.map((c) => [`<div class="iprev sm">${c.svg}</div> ${esc(c.name)}`, [...new Set(c.usedIn.flatMap((u) => (ctx.compsInFile[u[0]] || []).slice(0, 2)))].slice(0, 5).map(link).join(', ') || c.usedIn.slice(0, 2).map((u) => `<code>${u[0]}</code>`).join(', ') || '—']);
  const s2s = []; const perRoute = {}; for (const r of ctx.routes) for (const s of ctx.shots[r][1440]?.svgs || []) { const m = (s.cls || '').match(/lucide-([\w-]+)/); const k = m ? m[1] : 'svg próprio'; (perRoute[k] = perRoute[k] || {})[r] = 1; }
  for (const [k, rs] of Object.entries(perRoute).sort((a, b) => Object.keys(b[1]).length - Object.keys(a[1]).length)) s2s.push([`<code>${k}</code>`, Object.keys(rs).length, Object.keys(rs).slice(0, 8).map((r) => `<a href="#screen/${r}"><code>${esc(r)}</code></a>`).join(' ')]);
  const col = ctx.colors.bg.slice(0, 25).map((c) => [`<i class="sw" style="background:${esc(c.value)}"></i>`, `<code>${rgbToHex(c.value)}</code>`, Object.entries(c.tags).sort((a, b) => b[1] - a[1]).slice(0, 5).map(([t, n]) => `${t}×${n}`).join(' '), (() => { const tk = ctx.tokens.tokens.filter((t) => t.group === 'color' && Object.values(t.values).some((v) => rgbToHex(v).toLowerCase() === rgbToHex(c.value).toLowerCase())).map((t) => `<code>${t.name}</code>`); return tk.join(' ') || '—'; })()]);
  const fam = {}; for (const t of ctx.typoList) { const f = t.key.split('|')[0].split(',')[0].replace(/"/g, ''); for (const s of t.samples) for (const c of s.comps || []) if (ctx.compindex[c]) (fam[f] = fam[f] || {})[c] = (fam[f][c] || 0) + 1; }
  const f2c = Object.entries(fam).map(([f, cs]) => [`<code>${esc(f)}</code>`, Object.entries(cs).sort((a, b) => b[1] - a[1]).slice(0, 14).map(([c]) => link(c)).join(', ')]);
  return `<h1>Component Matrix</h1><h2>COMPONENTE → TELA</h2>${table(['Componente', 'Telas', 'Onde'], c2s, { filter: true })}<h2>COMPONENTE → ARQUIVO</h2>${table(['Componente', 'Arquivo:linha', 'Obs.'], c2f, { filter: true })}<h2>TOKEN → COMPONENTE</h2>${table(['Token', 'Usos', 'Componentes (por arquivo)'], t2c, { filter: true })}<h2>SVG → COMPONENTE</h2>${table(['Ícone próprio', 'Componentes que o usam'], s2c, { filter: true })}<h2>SVG → TELA (DOM real, lucide + próprios)</h2>${table(['Ícone', 'Telas', 'Onde'], s2s.slice(0, 120), { filter: true })}<h2>COR → COMPONENTE</h2><p>Fundos mais frequentes no DOM, com token equivalente quando o valor coincide.</p>${table(['Cor', 'Hex', 'Tags', 'Token'], col)}<h2>FONTE → COMPONENTE</h2>${table(['Família', 'Componentes (amostras medidas)'], f2c)}`;
}
export function sources(ctx) {
  const files = new Map(); for (const [n, ds] of Object.entries(ctx.compindex)) if (ctx.routesByComp[n]) for (const d of ds) (files.get(d.file) || files.set(d.file, []).get(d.file)).push(n);
  return `<h1>Source Files</h1><p>Arquivos que definem componentes renderizados nas telas percorridas.</p>${table(['Arquivo', 'Componentes'], [...files.entries()].sort().map(([f, ns]) => [`<code>${f}</code>`, ns.map(link).join(', ')]), { filter: true })}<h2>Arquivos-fonte do Design System</h2>${table(['Arquivo', 'Papel'], [['src/styles/globals.css', 'tokens, @font-face, keyframes, camadas base/componentes/utilitários'], ['src/config/brand.ts', 'marca em código'], ['src/lib/motion.ts', 'variantes de animação'], ['src/components/ui/', 'primitivos'], ['src/components/brand/BirthHubLogo.tsx', 'logo (gerado dos SVGs)'], ['src/components/icons/BrandIcons.tsx', 'ícones próprios'], ['identidade-visual/birthhub360/', 'ativos e tokens de marca (legado)']].map((r) => [`<code>${r[0]}</code>`, r[1]]))}`;
}
export function gallery(ctx) {
  const all = []; for (const r of ctx.pubFirst) for (const [w, h] of VPS) { const d = ctx.shots[r]?.[w]; if (d) all.push(`<figure class="gal" data-q="${esc(r)} ${w}"><a href="${A}/${d.screenshot}">${img(d.screenshot, r + ' ' + w, 'thumb')}</a><figcaption>${esc(r)} · ${w}×${h}<br><small>${d.timestamp}</small></figcaption></figure>`); }
  const extra = fs.existsSync(`${ROOT}/states`) ? fs.readdirSync(`${ROOT}/states`).filter((f) => f.endsWith('.png')).map((f) => `<figure class="gal" data-q="${f}"><a href="${A}/states/${f}">${img('states/' + f, f, 'thumb')}</a><figcaption>${f}</figcaption></figure>`).join('') : '';
  return `<h1>Screenshots</h1><input class="tfilter" id="galfilter" placeholder="filtrar por rota ou viewport…" aria-label="Filtrar screenshots"><div class="galgrid">${all.join('')}${extra}</div>`;
}
export function appendix(ctx, val) {
  return `<h1>Appendix</h1><h2>Checklist de aceitação</h2>${table(['Item', 'Status', 'Evidência'], val.map(([a, b, c]) => [a, b ? '<span class="ok">✔</span>' : '<span class="bad">✘</span>', c]))}<h2>Limites</h2><ul><li>Banco quase vazio: listas/tabelas/gráficos aparecem em estado vazio.</li><li>Rotas dinâmicas sem ID válido documentam apenas o estado de erro.</li><li>Screenshots são de viewport (não “full page”); a casca do app rola internamente.</li><li>Nomes de componentes vêm das fibras React em modo dev; componentes anônimos/de biblioteca não entram.</li><li>Contagem de uso de tokens é por regex (não detecta classes montadas dinamicamente).</li></ul><h2>Reprodução</h2><p>Scripts em <code>${A}/_tools/</code>: <code>capture.mjs</code> (rotas×viewports), <code>states.mjs</code>, <code>compshots.mjs</code>, <code>tokens.mjs</code>, <code>icons.mts</code>, <code>compindex.mjs</code>, <code>build.mjs</code>.</p>`;
}
